// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/pb/storage.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateEntityRequest struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Uuid       string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TypeID     int64  `protobuf:"varint,3,opt,name=typeID,proto3" json:"typeID,omitempty"`
	UserID     int64  `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	// Types that are valid to be assigned to Entity:
	//	*CreateEntityRequest_Account
	//	*CreateEntityRequest_CreditCard
	Entity               isCreateEntityRequest_Entity `protobuf_oneof:"entity"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CreateEntityRequest) Reset()         { *m = CreateEntityRequest{} }
func (m *CreateEntityRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEntityRequest) ProtoMessage()    {}
func (*CreateEntityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b273432c197719ba, []int{0}
}

func (m *CreateEntityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityRequest.Unmarshal(m, b)
}
func (m *CreateEntityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityRequest.Marshal(b, m, deterministic)
}
func (m *CreateEntityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityRequest.Merge(m, src)
}
func (m *CreateEntityRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEntityRequest.Size(m)
}
func (m *CreateEntityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityRequest proto.InternalMessageInfo

func (m *CreateEntityRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *CreateEntityRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateEntityRequest) GetTypeID() int64 {
	if m != nil {
		return m.TypeID
	}
	return 0
}

func (m *CreateEntityRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type isCreateEntityRequest_Entity interface {
	isCreateEntityRequest_Entity()
}

type CreateEntityRequest_Account struct {
	Account *Account `protobuf:"bytes,5,opt,name=account,proto3,oneof"`
}

type CreateEntityRequest_CreditCard struct {
	CreditCard *CreditCard `protobuf:"bytes,6,opt,name=credit_card,json=creditCard,proto3,oneof"`
}

func (*CreateEntityRequest_Account) isCreateEntityRequest_Entity() {}

func (*CreateEntityRequest_CreditCard) isCreateEntityRequest_Entity() {}

func (m *CreateEntityRequest) GetEntity() isCreateEntityRequest_Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *CreateEntityRequest) GetAccount() *Account {
	if x, ok := m.GetEntity().(*CreateEntityRequest_Account); ok {
		return x.Account
	}
	return nil
}

func (m *CreateEntityRequest) GetCreditCard() *CreditCard {
	if x, ok := m.GetEntity().(*CreateEntityRequest_CreditCard); ok {
		return x.CreditCard
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateEntityRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CreateEntityRequest_OneofMarshaler, _CreateEntityRequest_OneofUnmarshaler, _CreateEntityRequest_OneofSizer, []interface{}{
		(*CreateEntityRequest_Account)(nil),
		(*CreateEntityRequest_CreditCard)(nil),
	}
}

func _CreateEntityRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CreateEntityRequest)
	// entity
	switch x := m.Entity.(type) {
	case *CreateEntityRequest_Account:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Account); err != nil {
			return err
		}
	case *CreateEntityRequest_CreditCard:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreditCard); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CreateEntityRequest.Entity has unexpected type %T", x)
	}
	return nil
}

func _CreateEntityRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CreateEntityRequest)
	switch tag {
	case 5: // entity.account
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Account)
		err := b.DecodeMessage(msg)
		m.Entity = &CreateEntityRequest_Account{msg}
		return true, err
	case 6: // entity.credit_card
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreditCard)
		err := b.DecodeMessage(msg)
		m.Entity = &CreateEntityRequest_CreditCard{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CreateEntityRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CreateEntityRequest)
	// entity
	switch x := m.Entity.(type) {
	case *CreateEntityRequest_Account:
		s := proto.Size(x.Account)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CreateEntityRequest_CreditCard:
		s := proto.Size(x.CreditCard)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateEntityResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityResponse) Reset()         { *m = CreateEntityResponse{} }
func (m *CreateEntityResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEntityResponse) ProtoMessage()    {}
func (*CreateEntityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b273432c197719ba, []int{1}
}

func (m *CreateEntityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityResponse.Unmarshal(m, b)
}
func (m *CreateEntityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityResponse.Marshal(b, m, deterministic)
}
func (m *CreateEntityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityResponse.Merge(m, src)
}
func (m *CreateEntityResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEntityResponse.Size(m)
}
func (m *CreateEntityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityResponse proto.InternalMessageInfo

func (m *CreateEntityResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateEntityResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CreateEntityResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Account struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_b273432c197719ba, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreditCard struct {
	Number               string   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	HolderName           string   `protobuf:"bytes,2,opt,name=holder_name,json=holderName,proto3" json:"holder_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreditCard) Reset()         { *m = CreditCard{} }
func (m *CreditCard) String() string { return proto.CompactTextString(m) }
func (*CreditCard) ProtoMessage()    {}
func (*CreditCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_b273432c197719ba, []int{3}
}

func (m *CreditCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditCard.Unmarshal(m, b)
}
func (m *CreditCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditCard.Marshal(b, m, deterministic)
}
func (m *CreditCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditCard.Merge(m, src)
}
func (m *CreditCard) XXX_Size() int {
	return xxx_messageInfo_CreditCard.Size(m)
}
func (m *CreditCard) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditCard.DiscardUnknown(m)
}

var xxx_messageInfo_CreditCard proto.InternalMessageInfo

func (m *CreditCard) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *CreditCard) GetHolderName() string {
	if m != nil {
		return m.HolderName
	}
	return ""
}

type FindOneData struct {
	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Identifier string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	TypeID     int64  `protobuf:"varint,3,opt,name=typeID,proto3" json:"typeID,omitempty"`
	// Types that are valid to be assigned to Entity:
	//	*FindOneData_Account
	//	*FindOneData_CreditCard
	Entity               isFindOneData_Entity `protobuf_oneof:"entity"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FindOneData) Reset()         { *m = FindOneData{} }
func (m *FindOneData) String() string { return proto.CompactTextString(m) }
func (*FindOneData) ProtoMessage()    {}
func (*FindOneData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b273432c197719ba, []int{4}
}

func (m *FindOneData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneData.Unmarshal(m, b)
}
func (m *FindOneData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneData.Marshal(b, m, deterministic)
}
func (m *FindOneData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneData.Merge(m, src)
}
func (m *FindOneData) XXX_Size() int {
	return xxx_messageInfo_FindOneData.Size(m)
}
func (m *FindOneData) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneData.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneData proto.InternalMessageInfo

func (m *FindOneData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FindOneData) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *FindOneData) GetTypeID() int64 {
	if m != nil {
		return m.TypeID
	}
	return 0
}

type isFindOneData_Entity interface {
	isFindOneData_Entity()
}

type FindOneData_Account struct {
	Account *Account `protobuf:"bytes,4,opt,name=account,proto3,oneof"`
}

type FindOneData_CreditCard struct {
	CreditCard *CreditCard `protobuf:"bytes,5,opt,name=credit_card,json=creditCard,proto3,oneof"`
}

func (*FindOneData_Account) isFindOneData_Entity() {}

func (*FindOneData_CreditCard) isFindOneData_Entity() {}

func (m *FindOneData) GetEntity() isFindOneData_Entity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *FindOneData) GetAccount() *Account {
	if x, ok := m.GetEntity().(*FindOneData_Account); ok {
		return x.Account
	}
	return nil
}

func (m *FindOneData) GetCreditCard() *CreditCard {
	if x, ok := m.GetEntity().(*FindOneData_CreditCard); ok {
		return x.CreditCard
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FindOneData) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FindOneData_OneofMarshaler, _FindOneData_OneofUnmarshaler, _FindOneData_OneofSizer, []interface{}{
		(*FindOneData_Account)(nil),
		(*FindOneData_CreditCard)(nil),
	}
}

func _FindOneData_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FindOneData)
	// entity
	switch x := m.Entity.(type) {
	case *FindOneData_Account:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Account); err != nil {
			return err
		}
	case *FindOneData_CreditCard:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreditCard); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FindOneData.Entity has unexpected type %T", x)
	}
	return nil
}

func _FindOneData_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FindOneData)
	switch tag {
	case 4: // entity.account
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Account)
		err := b.DecodeMessage(msg)
		m.Entity = &FindOneData_Account{msg}
		return true, err
	case 5: // entity.credit_card
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreditCard)
		err := b.DecodeMessage(msg)
		m.Entity = &FindOneData_CreditCard{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FindOneData_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FindOneData)
	// entity
	switch x := m.Entity.(type) {
	case *FindOneData_Account:
		s := proto.Size(x.Account)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *FindOneData_CreditCard:
		s := proto.Size(x.CreditCard)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type FindOneRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOneRequest) Reset()         { *m = FindOneRequest{} }
func (m *FindOneRequest) String() string { return proto.CompactTextString(m) }
func (*FindOneRequest) ProtoMessage()    {}
func (*FindOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b273432c197719ba, []int{5}
}

func (m *FindOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneRequest.Unmarshal(m, b)
}
func (m *FindOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneRequest.Marshal(b, m, deterministic)
}
func (m *FindOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneRequest.Merge(m, src)
}
func (m *FindOneRequest) XXX_Size() int {
	return xxx_messageInfo_FindOneRequest.Size(m)
}
func (m *FindOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneRequest proto.InternalMessageInfo

func (m *FindOneRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type FindOneResponse struct {
	Status               int64        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *FindOneData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FindOneResponse) Reset()         { *m = FindOneResponse{} }
func (m *FindOneResponse) String() string { return proto.CompactTextString(m) }
func (*FindOneResponse) ProtoMessage()    {}
func (*FindOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b273432c197719ba, []int{6}
}

func (m *FindOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOneResponse.Unmarshal(m, b)
}
func (m *FindOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOneResponse.Marshal(b, m, deterministic)
}
func (m *FindOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOneResponse.Merge(m, src)
}
func (m *FindOneResponse) XXX_Size() int {
	return xxx_messageInfo_FindOneResponse.Size(m)
}
func (m *FindOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindOneResponse proto.InternalMessageInfo

func (m *FindOneResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FindOneResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FindOneResponse) GetData() *FindOneData {
	if m != nil {
		return m.Data
	}
	return nil
}

type FindByUserRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByUserRequest) Reset()         { *m = FindByUserRequest{} }
func (m *FindByUserRequest) String() string { return proto.CompactTextString(m) }
func (*FindByUserRequest) ProtoMessage()    {}
func (*FindByUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b273432c197719ba, []int{7}
}

func (m *FindByUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByUserRequest.Unmarshal(m, b)
}
func (m *FindByUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByUserRequest.Marshal(b, m, deterministic)
}
func (m *FindByUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByUserRequest.Merge(m, src)
}
func (m *FindByUserRequest) XXX_Size() int {
	return xxx_messageInfo_FindByUserRequest.Size(m)
}
func (m *FindByUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByUserRequest proto.InternalMessageInfo

func (m *FindByUserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type FindByUserResponse struct {
	Status               int64          `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Data                 []*FindOneData `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FindByUserResponse) Reset()         { *m = FindByUserResponse{} }
func (m *FindByUserResponse) String() string { return proto.CompactTextString(m) }
func (*FindByUserResponse) ProtoMessage()    {}
func (*FindByUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b273432c197719ba, []int{8}
}

func (m *FindByUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByUserResponse.Unmarshal(m, b)
}
func (m *FindByUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByUserResponse.Marshal(b, m, deterministic)
}
func (m *FindByUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByUserResponse.Merge(m, src)
}
func (m *FindByUserResponse) XXX_Size() int {
	return xxx_messageInfo_FindByUserResponse.Size(m)
}
func (m *FindByUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByUserResponse proto.InternalMessageInfo

func (m *FindByUserResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FindByUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FindByUserResponse) GetData() []*FindOneData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateEntityRequest)(nil), "storage.CreateEntityRequest")
	proto.RegisterType((*CreateEntityResponse)(nil), "storage.CreateEntityResponse")
	proto.RegisterType((*Account)(nil), "storage.Account")
	proto.RegisterType((*CreditCard)(nil), "storage.CreditCard")
	proto.RegisterType((*FindOneData)(nil), "storage.FindOneData")
	proto.RegisterType((*FindOneRequest)(nil), "storage.FindOneRequest")
	proto.RegisterType((*FindOneResponse)(nil), "storage.FindOneResponse")
	proto.RegisterType((*FindByUserRequest)(nil), "storage.FindByUserRequest")
	proto.RegisterType((*FindByUserResponse)(nil), "storage.FindByUserResponse")
}

func init() { proto.RegisterFile("pkg/pb/storage.proto", fileDescriptor_b273432c197719ba) }

var fileDescriptor_b273432c197719ba = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0xa6, 0xfc, 0x75, 0x3d, 0x35, 0xb8, 0x9e, 0x25, 0x6e, 0x83, 0x7f, 0xa4, 0xf1, 0x82, 0x8b,
	0x0d, 0x24, 0x98, 0x78, 0x63, 0x62, 0x22, 0xb0, 0xba, 0x7b, 0xa1, 0x26, 0x5d, 0xbd, 0xf1, 0x86,
	0x0c, 0x9d, 0x23, 0x4e, 0x84, 0xb6, 0xce, 0x4c, 0x35, 0x3c, 0xa0, 0xef, 0xa2, 0x6f, 0x61, 0xda,
	0x4e, 0x4b, 0x61, 0x5d, 0x13, 0xf4, 0x8e, 0xef, 0x9c, 0x33, 0xc3, 0xf7, 0x73, 0x3a, 0xd0, 0x8d,
	0xbf, 0x2c, 0x47, 0xf1, 0x62, 0xa4, 0x74, 0x24, 0xd9, 0x92, 0x86, 0xb1, 0x8c, 0x74, 0x84, 0xb6,
	0x81, 0xde, 0x2f, 0x0b, 0x4e, 0xa6, 0x92, 0x98, 0xa6, 0xf3, 0x50, 0x0b, 0xbd, 0xf1, 0xe9, 0x6b,
	0x42, 0x4a, 0xe3, 0x23, 0x00, 0xc1, 0x29, 0xd4, 0xe2, 0x93, 0x20, 0xe9, 0x5a, 0x7d, 0x6b, 0x70,
	0xcb, 0xaf, 0x54, 0x10, 0xa1, 0x99, 0x24, 0x82, 0xbb, 0xf5, 0xac, 0x93, 0xfd, 0xc6, 0x7b, 0xd0,
	0xd6, 0x9b, 0x98, 0x2e, 0x67, 0x6e, 0xa3, 0x6f, 0x0d, 0x1a, 0xbe, 0x41, 0x69, 0x3d, 0x51, 0x24,
	0x2f, 0x67, 0x6e, 0x33, 0xaf, 0xe7, 0x08, 0xcf, 0xc0, 0x66, 0x41, 0x10, 0x25, 0xa1, 0x76, 0x5b,
	0x7d, 0x6b, 0xe0, 0x8c, 0x8f, 0x87, 0x05, 0xcb, 0x97, 0x79, 0xfd, 0xa2, 0xe6, 0x17, 0x23, 0xf8,
	0x0c, 0x9c, 0x40, 0x12, 0x17, 0x7a, 0x1e, 0x30, 0xc9, 0xdd, 0x76, 0x76, 0xe2, 0xa4, 0x3c, 0x31,
	0xcd, 0x7a, 0x53, 0x26, 0xf9, 0x45, 0xcd, 0x87, 0xa0, 0x44, 0x93, 0x23, 0x68, 0x53, 0x26, 0xcd,
	0x7b, 0x0f, 0xdd, 0x5d, 0xa9, 0x2a, 0x8e, 0x42, 0x45, 0x29, 0x3f, 0xa5, 0x99, 0x4e, 0x54, 0xa6,
	0xb3, 0xe1, 0x1b, 0x84, 0x5d, 0x68, 0x91, 0x94, 0x91, 0x34, 0x22, 0x73, 0x80, 0x1d, 0xa8, 0x0b,
	0x6e, 0x14, 0xd6, 0x05, 0xf7, 0x9e, 0x83, 0x6d, 0xd8, 0xa6, 0x07, 0x56, 0xd1, 0x52, 0x84, 0xc6,
	0xaf, 0x1c, 0x60, 0x0f, 0x8e, 0x62, 0xa6, 0xd4, 0xf7, 0x48, 0x16, 0x76, 0x95, 0xd8, 0x3b, 0x07,
	0xd8, 0x12, 0x4f, 0x89, 0x84, 0xc9, 0x7a, 0x51, 0x1a, 0x6e, 0x10, 0x3e, 0x06, 0xe7, 0x73, 0xb4,
	0xe2, 0x24, 0xe7, 0x21, 0x5b, 0x93, 0xb9, 0x04, 0xf2, 0xd2, 0x5b, 0xb6, 0x26, 0xef, 0x87, 0x05,
	0xce, 0x2b, 0x11, 0xf2, 0x77, 0x21, 0xcd, 0x98, 0x66, 0x86, 0xa3, 0x55, 0x70, 0xdc, 0x4b, 0xb3,
	0x7e, 0x2d, 0xcd, 0x9b, 0x92, 0xab, 0x24, 0xd4, 0x3c, 0x38, 0xa1, 0xd6, 0xe1, 0x09, 0x3d, 0x81,
	0x8e, 0x91, 0x51, 0xec, 0x61, 0xb1, 0x67, 0xd6, 0x76, 0xcf, 0x3c, 0x01, 0x77, 0xca, 0xa9, 0x7f,
	0x8a, 0x70, 0x00, 0x4d, 0xce, 0x34, 0xcb, 0xc4, 0x3a, 0xe3, 0x6e, 0xc9, 0xb0, 0x62, 0xa1, 0x9f,
	0x4d, 0x78, 0x67, 0x70, 0x37, 0x2d, 0x4e, 0x36, 0x1f, 0x14, 0xc9, 0x82, 0xd3, 0x29, 0xd8, 0xe9,
	0x06, 0xcf, 0x4b, 0x8b, 0xf3, 0x85, 0xe6, 0xde, 0x0a, 0xb0, 0x3a, 0xfd, 0x9f, 0xdc, 0x1a, 0x7f,
	0xe7, 0x36, 0xfe, 0x69, 0x41, 0xe7, 0x2a, 0xef, 0x5e, 0x91, 0xfc, 0x26, 0x02, 0xc2, 0x37, 0x70,
	0xbb, 0xba, 0xe1, 0xf8, 0xa0, 0x6a, 0xfe, 0xfe, 0x37, 0xde, 0x7b, 0x78, 0x43, 0x37, 0xe7, 0xed,
	0xd5, 0xf0, 0x05, 0xd8, 0xe6, 0x6f, 0xf1, 0x74, 0x9f, 0x48, 0x71, 0x89, 0x7b, 0xbd, 0x51, 0x9e,
	0x7f, 0x0d, 0xb0, 0xf5, 0x03, 0x7b, 0x3b, 0x93, 0x3b, 0x96, 0xf6, 0xee, 0xff, 0xb1, 0x57, 0x5c,
	0x34, 0xc1, 0x8f, 0xc7, 0xc3, 0x51, 0xfa, 0x90, 0x99, 0xa9, 0x51, 0xbc, 0x58, 0xb4, 0xb3, 0x97,
	0xec, 0xe9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x62, 0x2b, 0x09, 0xe1, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageServiceClient interface {
	CreateEntity(ctx context.Context, in *CreateEntityRequest, opts ...grpc.CallOption) (*CreateEntityResponse, error)
	FindOne(ctx context.Context, in *FindOneRequest, opts ...grpc.CallOption) (*FindOneResponse, error)
	FindByUser(ctx context.Context, in *FindByUserRequest, opts ...grpc.CallOption) (*FindByUserResponse, error)
}

type storageServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageServiceClient(cc *grpc.ClientConn) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) CreateEntity(ctx context.Context, in *CreateEntityRequest, opts ...grpc.CallOption) (*CreateEntityResponse, error) {
	out := new(CreateEntityResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/CreateEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) FindOne(ctx context.Context, in *FindOneRequest, opts ...grpc.CallOption) (*FindOneResponse, error) {
	out := new(FindOneResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/FindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) FindByUser(ctx context.Context, in *FindByUserRequest, opts ...grpc.CallOption) (*FindByUserResponse, error) {
	out := new(FindByUserResponse)
	err := c.cc.Invoke(ctx, "/storage.StorageService/FindByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
type StorageServiceServer interface {
	CreateEntity(context.Context, *CreateEntityRequest) (*CreateEntityResponse, error)
	FindOne(context.Context, *FindOneRequest) (*FindOneResponse, error)
	FindByUser(context.Context, *FindByUserRequest) (*FindByUserResponse, error)
}

func RegisterStorageServiceServer(s *grpc.Server, srv StorageServiceServer) {
	s.RegisterService(&_StorageService_serviceDesc, srv)
}

func _StorageService_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/CreateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateEntity(ctx, req.(*CreateEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_FindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).FindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/FindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).FindOne(ctx, req.(*FindOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_FindByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).FindByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.StorageService/FindByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).FindByUser(ctx, req.(*FindByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEntity",
			Handler:    _StorageService_CreateEntity_Handler,
		},
		{
			MethodName: "FindOne",
			Handler:    _StorageService_FindOne_Handler,
		},
		{
			MethodName: "FindByUser",
			Handler:    _StorageService_FindByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pb/storage.proto",
}
